"""Create reproducible synthetic research; generate unique local demo passwords."""
import sys, json, secrets, os
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]/'backend'))
from sqlalchemy import select
from app.models.database import *
from app.core.security import hash_password
from app.core.config import DATA
from app.services.storage import storage
from app.services.processing import process_job

def seed():
    Base.metadata.create_all(engine)
    jobs=[]
    with SessionLocal() as db:
        if db.scalar(select(User).limit(1)): return
        accounts=[]
        for role,name in [('admin','Dr. Ananya Rao'),('researcher','Dr. Arjun Sen'),('content_manager','Meera Nair')]:
            password=secrets.token_urlsafe(12)
            email=f'{role}@polaris.demo'
            if role=='admin' and os.getenv('ADMIN_PASSWORD'):
                password=os.environ['ADMIN_PASSWORD']
                email=os.environ.get('ADMIN_EMAIL', 'admin@polaris.demo').strip().lower()
                if len(password)<12: raise ValueError('ADMIN_PASSWORD must contain at least 12 characters')
            user=User(name=name,email=email,role=role,password=hash_password(password)); db.add(user); db.flush()
            accounts.append({'email':user.email,'password':password,'role':role,'name':name})
            if role=='admin': owner=user.id
        DATA.joinpath('demo-accounts.json').write_text(json.dumps(accounts,indent=2))
        stations=[('Bharati',-69.408,76.187,'Antarctic','Larsemann Hills','Oceanography, geology and climate observations'),('Maitri',-70.765,11.735,'Antarctic','Schirmacher Oasis','Atmospheric science and glaciology'),('Himadri',78.923,11.922,'Arctic','Ny-Ålesund, Svalbard','Arctic atmosphere, fjords and ecosystems')]
        for name,lat,lon,region,location,activities in stations:
            db.add(Resource(kind='station',title=name,data={'lat':lat,'lon':lon,'region':region,'location':location,'activities':activities,'demo':True,'description':'Station location used for demonstration. Activities and linked records are synthetic examples.'}))
        topics=[('Antarctic ice-sheet dynamics and coastal change','Glaciology','Antarctic','Bharati','ice glacier melt coastal','The synthetic observations show seasonal variation in surface melt across three coastal sampling sites.','Satellite imagery was compared with monthly field measurements.'),('Southern Ocean carbon exchange observations','Oceanography','Antarctic','Bharati','ocean carbon exchange phytoplankton','The demonstration dataset records differences in dissolved carbon between nearshore sampling locations.','Water samples were collected along a repeated coastal transect.'),('Arctic atmospheric aerosol monitoring','Atmospheric science','Arctic','Himadri','aerosol atmosphere black carbon arctic','Synthetic aerosol concentrations vary with the sampling month and local wind conditions.','Ground-based optical instruments measured aerosol scattering each day.'),('Microbial diversity in polar lake ecosystems','Polar biology','Antarctic','Maitri','microbial biology lake diversity','The synthetic lake samples contain distinct microbial groups across depth intervals.','Demonstration samples were analyzed using an illustrative DNA sequencing workflow.'),('Permafrost temperature and active-layer variability','Climate science','Arctic','Himadri','permafrost temperature climate warming','The synthetic series illustrates seasonal temperature variability within a shallow permafrost profile.','Temperature probes recorded hourly values at three depths.'),('Antarctic expedition field observations 2024','Expedition Reports','Antarctic','Maitri','expedition field observations station','The demonstration expedition completed coastal observations, lake sampling and station instrument maintenance.','Field teams used repeated sampling and documented instrument calibration.'),('Sea-ice extent and seasonal variability','Climate science','Antarctic','Bharati','sea ice seasonal extent climate','Synthetic sea-ice measurements demonstrate a seasonal cycle, with a minimum in austral summer.','Monthly ice-edge positions were compared within a fixed study region.'),('Svalbard fjord water-column profiles','Oceanography','Arctic','Himadri','fjord salinity water ocean arctic','The synthetic profiles show salinity differences between shallow and deeper water layers.','Conductivity-temperature-depth profiles were recorded at four fjord sites.')]
        for i,(title,domain,region,station,keywords,finding,method) in enumerate(topics):
            year=2021+i%5; expedition=f'Polar Research Expedition {year} · {region}'
            text=f'{title}\nDEMO / SYNTHETIC RESEARCH — NOT OFFICIAL GOVERNMENT DATA\nAuthors: Ananya Rao; Arjun Sen\nOrganization: POLARIS Demonstration Research Group\nDate: {year}-11-15\nExpedition: {expedition}\nStation: {station}\nAbstract: This synthetic study explores {keywords} to demonstrate the POLARIS research workflow. {finding}\nObjective: Compare repeated observations and document variability in {keywords}.\nMethodology: {method}\nFindings: {finding}\nLimitations: All measurements and conclusions in this record are synthetic and cannot support real scientific claims.\nDatasets: Synthetic {domain} observations\nReferences: POLARIS demonstration protocol, version 1.\n\nEducation note: Antarctica is a continent surrounding the South Pole. The Arctic is a region surrounding the North Pole. Glaciology is the study of ice and glaciers. Oceanography studies the ocean. These definitions provide educational context; the observations above are synthetic.'
            doc=Document(title=title,owner_id=owner,category='Expedition Reports' if domain=='Expedition Reports' else 'Research Papers',domain=domain,region=region,year=year,moderation='PUBLISHED',demo=True); db.add(doc); db.flush()
            key=uid()+'.txt'; storage().put(key,text.encode()); db.add(Version(document_id=doc.id,number=1,filename=f'synthetic-study-{i+1}.txt',storage_key=key,mime='text/plain',size=len(text.encode()))); job=Job(document_id=doc.id); db.add(job); db.flush(); jobs.append(job.id)
        for i in range(4):
            region='Arctic' if i==3 else 'Antarctic'; year=2025-i
            db.add(Resource(kind='expedition',title=f'Polar Research Expedition {year} · {region}',data={'year':year,'region':region,'duration':'November – March · 120 days','scientists':['Dr. Ananya Rao','Dr. Arjun Sen','Dr. Meera Iyer'],'objectives':['Observe seasonal environmental variability','Collect repeatable field measurements','Maintain station instruments'],'areas':['Climate science','Oceanography','Glaciology'],'stations':['Himadri'] if region=='Arctic' else ['Maitri','Bharati'],'route':[[78.2,15.6],[78.923,11.922]] if region=='Arctic' else [[-33.92,18.42],[-70.765,11.735],[-69.408,76.187]],'findings':'Synthetic field programme completed. See linked demonstration reports for source-specific findings.','timeline':[{'stage':s,'date':f'{year}-{m:02d}-15'} for s,m in [('Planning',6),('Departure',10),('Research Station',11),('Field Research',11),('Data Collection',12),('Return',12),('Publications',12)]],'demo':True}))
        for i,(name,lat,lon,region,_,_) in enumerate(stations):
            rows='date,temperature_c,salinity_psu,synthetic\n'+'\n'.join(f'2025-{m:02d}-01,{-15+m+i},{32+m/10},true' for m in range(1,13))
            db.add(Resource(kind='dataset',title=f'{name} seasonal observation series',data={'station':name,'region':region,'lat':lat,'lon':lon,'format':'CSV','rows':12,'variables':['temperature_c','salinity_psu'],'license':'CC0 · synthetic data only','description':'Twelve synthetic monthly observations for testing and education. Not suitable for scientific inference.','csv':rows,'demo':True}))
        lessons=[('Antarctica','Antarctica is a continent surrounding the South Pole. Ice covers most of its surface. Scientists study its ice, atmosphere, ocean and ecosystems.'),('Arctic','The Arctic surrounds the North Pole and includes an ocean bordered by land. Sea ice changes seasonally.'),('Climate science','Climate science examines long-term patterns in temperature, precipitation and other environmental measurements.'),('Glaciology','Glaciology is the study of ice and glaciers. Researchers measure ice thickness, movement and melt.'),('Oceanography','Oceanography studies ocean water, circulation, chemistry and living systems.'),('Polar biology','Polar biology explores organisms and ecosystems in cold regions.'),('Atmospheric science','Atmospheric science investigates air, clouds, aerosols and the processes shaping weather and climate.'),('Indian polar research','Use the station map to explore Bharati, Maitri and Himadri. Linked programmes here are synthetic demonstration records.')]
        for i,(title,content) in enumerate(lessons): db.add(Resource(kind='lesson',title=title,data={'content':content,'difficulty':'Beginner' if i<4 else 'Intermediate','duration':'4 min','demo':True}))
        for title,content in [('Albedo','The fraction of incoming light reflected by a surface.'),('Glaciology','The scientific study of ice and glaciers.'),('Permafrost','Ground that remains at or below 0°C for at least two consecutive years.'),('Sea ice','Ice formed by the freezing of seawater.')]: db.add(Resource(kind='glossary',title=title,data={'definition':content}))
        db.add(Resource(kind='quiz',title='Polar foundations',data={'difficulty':'Beginner','demo':True,'questions':[{'question':'Which region surrounds the South Pole?','options':['Antarctica','The Arctic','The Himalayas'],'answer':0,'explanation':'The Antarctica lesson identifies it as the continent surrounding the South Pole.','source':'Antarctica lesson'},{'question':'What does glaciology study?','options':['Volcanoes','Ice and glaciers','Desert soils'],'answer':1,'explanation':'Glaciology is the study of ice and glaciers.','source':'Glaciology lesson'},{'question':'Can synthetic demo measurements establish real scientific findings?','options':['Yes, without checking','Only when formatted as a chart','No'],'answer':2,'explanation':'Synthetic demonstration measurements are not scientific evidence.','source':'All seeded research source limitations'}]}))
        db.commit()
    for job in jobs: process_job(job)
    print('Seeded synthetic research and generated local demo accounts.')
if __name__=='__main__': seed()
